const countriesData = [
  {
    country: "Abkhazia",
    countryCodes: ["7840"],
    flag: "./src/ab.svg",
    isoCode2: "AB",
    isoCode3: "ABH",
  },
  {
    country: "Afghanistan",
    countryCodes: ["93"],
    flag: "./src/af.svg",
    isoCode2: "AF",
    isoCode3: "AFG",
  },
  {
    country: "Aland Islands",
    countryCodes: ["358 18"],
    flag: "./src/ax.svg",
    isoCode2: "AX",
    isoCode3: "ALA",
  },
  {
    country: "Albania",
    countryCodes: ["355"],
    flag: "./src/al.svg",
    isoCode2: "AL",
    isoCode3: "ALB",
  },
  {
    country: "Algeria",
    countryCodes: ["213"],
    flag: "./src/dz.svg",
    isoCode2: "DZ",
    isoCode3: "DZA",
  },
  {
    country: "American Samoa",
    countryCodes: ["1-684"],
    flag: "./src/as.svg",
    isoCode2: "AS",
    isoCode3: "ASM",
  },
  {
    country: "Andorra",
    countryCodes: ["376"],
    flag: "./src/ad.svg",
    isoCode2: "AD",
    isoCode3: "AND",
  },
  {
    country: "Angola",
    countryCodes: ["244"],
    flag: "./src/ao.svg",
    isoCode2: "AO",
    isoCode3: "AGO",
  },
  {
    country: "Anguilla",
    countryCodes: ["1-264"],
    flag: "./src/ai.svg",
    isoCode2: "AI",
    isoCode3: "AIA",
  },
  {
    country: "Antarctica",
    countryCodes: ["672"],
    flag: "./src/aq.svg",
    isoCode2: "AQ",
    isoCode3: "ATA",
  },
  {
    country: "Antigua and Barbuda",
    countryCodes: ["1-268"],
    flag: "./src/ag.svg",
    isoCode2: "AG",
    isoCode3: "ATG",
  },
  {
    country: "Argentina",
    countryCodes: ["54"],
    flag: "./src/ar.svg",
    isoCode2: "AR",
    isoCode3: "ARG",
  },
  {
    country: "Armenia",
    countryCodes: ["374"],
    flag: "./src/am.svg",
    isoCode2: "AM",
    isoCode3: "ARM",
  },
  {
    country: "Aruba",
    countryCodes: ["297"],
    flag: "./src/aw.svg",
    isoCode2: "AW",
    isoCode3: "ABW",
  },
  {
    country: "Australia",
    countryCodes: ["61"],
    flag: "./src/au.svg",
    isoCode2: "AU",
    isoCode3: "AUS",
  },
  {
    country: "Austria",
    countryCodes: ["43"],
    flag: "./src/at.svg",
    isoCode2: "AT",
    isoCode3: "AUT",
  },
  {
    country: "Azerbaijan",
    countryCodes: ["994"],
    flag: "./src/az.svg",
    isoCode2: "AZ",
    isoCode3: "AZE",
  },
  {
    country: "Bahamas",
    countryCodes: ["1-242"],
    flag: "./src/bs.svg",
    isoCode2: "BS",
    isoCode3: "BHS",
  },
  {
    country: "Bahrain",
    countryCodes: ["973"],
    flag: "./src/bh.svg",
    isoCode2: "BH",
    isoCode3: "BHR",
  },
  {
    country: "Bangladesh",
    countryCodes: ["880"],
    flag: "./src/bd.svg",
    isoCode2: "BD",
    isoCode3: "BGD",
  },
  {
    country: "Barbados",
    countryCodes: ["1-246"],
    flag: "./src/bb.svg",
    isoCode2: "BB",
    isoCode3: "BRB",
  },
  {
    country: "Belarus",
    countryCodes: ["375"],
    flag: "./src/by.svg",
    isoCode2: "BY",
    isoCode3: "BLR",
  },
  {
    country: "Belgium",
    countryCodes: ["32"],
    flag: "./src/be.svg",
    isoCode2: "BE",
    isoCode3: "BEL",
  },
  {
    country: "Belize",
    countryCodes: ["501"],
    flag: "./src/bz.svg",
    isoCode2: "BZ",
    isoCode3: "BLZ",
  },
  {
    country: "Benin",
    countryCodes: ["229"],
    flag: "./src/bj.svg",
    isoCode2: "BJ",
    isoCode3: "BEN",
  },
  {
    country: "Bermuda",
    countryCodes: ["1-441"],
    flag: "./src/bm.svg",
    isoCode2: "BM",
    isoCode3: "BMU",
  },
  {
    country: "Bhutan",
    countryCodes: ["975"],
    flag: "./src/bt.svg",
    isoCode2: "BT",
    isoCode3: "BTN",
  },
  {
    country: "Bolivia",
    countryCodes: ["591"],
    flag: "./src/bo.svg",
    isoCode2: "BO",
    isoCode3: "BOL",
  },
  {
    country: "Bosnia and Herzegovina",
    countryCodes: ["387"],
    flag: "./src/ba.svg",
    isoCode2: "BA",
    isoCode3: "BIH",
  },
  {
    country: "Bouvet Island",
    countryCodes: ["55"],
    flag: "./src/bv.svg",
    isoCode2: "BV",
    isoCode3: "BVT",
  },
  {
    country: "Botswana",
    countryCodes: ["267"],
    flag: "./src/bw.svg",
    isoCode2: "BW",
    isoCode3: "BWA",
  },
  {
    country: "Brazil",
    countryCodes: ["55"],
    flag: "./src/br.svg",
    isoCode2: "BR",
    isoCode3: "BRA",
  },
  {
    country: "British Indian Ocean Territory",
    countryCodes: ["246"],
    flag: "./src/io.svg",
    isoCode2: "IO",
    isoCode3: "IOT",
  },
  {
    country: "British Virgin Islands",
    countryCodes: ["1-284"],
    flag: "./src/vg.svg",
    isoCode2: "VG",
    isoCode3: "VGB",
  },
  {
    country: "Brunei",
    countryCodes: ["673"],
    flag: "./src/bn.svg",
    isoCode2: "BN",
    isoCode3: "BRN",
  },
  {
    country: "Bulgaria",
    countryCodes: ["359"],
    flag: "./src/bg.svg",
    isoCode2: "BG",
    isoCode3: "BGR",
  },
  {
    country: "Burkina Faso",
    countryCodes: ["226"],
    flag: "./src/bf.svg",
    isoCode2: "BF",
    isoCode3: "BFA",
  },
  {
    country: "Burundi",
    countryCodes: ["257"],
    flag: "./src/bi.svg",
    isoCode2: "BI",
    isoCode3: "BDI",
  },
  {
    country: "Cambodia",
    countryCodes: ["855"],
    flag: "./src/kh.svg",
    isoCode2: "KH",
    isoCode3: "KHM",
  },
  {
    country: "Cameroon",
    countryCodes: ["237"],
    flag: "./src/cm.svg",
    isoCode2: "CM",
    isoCode3: "CMR",
  },
  {
    country: "Canada",
    countryCodes: ["1"],
    flag: "./src/ca.svg",
    isoCode2: "CA",
    isoCode3: "CAN",
  },
  {
    country: "Cape Verde",
    countryCodes: ["238"],
    flag: "./src/cv.svg",
    isoCode2: "CV",
    isoCode3: "CPV",
  },
  {
    country: "Cayman Islands",
    countryCodes: ["1-345"],
    flag: "./src/ky.svg",
    isoCode2: "KY",
    isoCode3: "CYM",
  },
  {
    country: "Central African Republic",
    countryCodes: ["236"],
    flag: "./src/cf.svg",
    isoCode2: "CF",
    isoCode3: "CAF",
  },
  {
    country: "Chad",
    countryCodes: ["235"],
    flag: "./src/td.svg",
    isoCode2: "TD",
    isoCode3: "TCD",
  },
  {
    country: "Chile",
    countryCodes: ["56"],
    flag: "./src/cl.svg",
    isoCode2: "CL",
    isoCode3: "CHL",
  },
  {
    country: "China",
    countryCodes: ["86"],
    flag: "./src/cn.svg",
    isoCode2: "CN",
    isoCode3: "CHN",
  },
  {
    country: "Christmas Island",
    countryCodes: ["61"],
    flag: "./src/cx.svg",
    isoCode2: "CX",
    isoCode3: "CXR",
  },
  {
    country: "Cocos Islands",
    countryCodes: ["61"],
    flag: "./src/cc.svg",
    isoCode2: "CC",
    isoCode3: "CCK",
  },
  {
    country: "Colombia",
    countryCodes: ["57"],
    flag: "./src/co.svg",
    isoCode2: "CO",
    isoCode3: "COL",
  },
  {
    country: "Comoros",
    countryCodes: ["269"],
    flag: "./src/km.svg",
    isoCode2: "KM",
    isoCode3: "COM",
  },
  {
    country: "Cook Islands",
    countryCodes: ["682"],
    flag: "./src/ck.svg",
    isoCode2: "CK",
    isoCode3: "COK",
  },
  {
    country: "Costa Rica",
    countryCodes: ["506"],
    flag: "./src/cr.svg",
    isoCode2: "CR",
    isoCode3: "CRI",
  },
  {
    country: "Croatia",
    countryCodes: ["385"],
    flag: "./src/hr.svg",
    isoCode2: "HR",
    isoCode3: "HRV",
  },
  {
    country: "Cuba",
    countryCodes: ["53"],
    flag: "./src/cu.svg",
    isoCode2: "CU",
    isoCode3: "CUB",
  },
  {
    country: "Curacao",
    countryCodes: ["599"],
    flag: "./src/cw.svg",
    isoCode2: "CW",
    isoCode3: "CUW",
  },
  {
    country: "Cyprus",
    countryCodes: ["357"],
    flag: "./src/cy.svg",
    isoCode2: "CY",
    isoCode3: "CYP",
  },
  {
    country: "Czech Republic",
    countryCodes: ["420"],
    flag: "./src/cz.svg",
    isoCode2: "CZ",
    isoCode3: "CZE",
  },
  {
    country: "Democratic Republic of the Congo",
    countryCodes: ["243"],
    flag: "./src/cd.svg",
    isoCode2: "CD",
    isoCode3: "COD",
  },
  {
    country: "Denmark",
    countryCodes: ["45"],
    flag: "./src/dk.svg",
    isoCode2: "DK",
    isoCode3: "DNK",
  },
  {
    country: "Djibouti",
    countryCodes: ["253"],
    flag: "./src/dj.svg",
    isoCode2: "DJ",
    isoCode3: "DJI",
  },
  {
    country: "Dominica",
    countryCodes: ["1-767"],
    flag: "./src/dm.svg",
    isoCode2: "DM",
    isoCode3: "DMA",
  },
  {
    country: "Dominican Republic",
    countryCodes: ["1-809", "1-829", "1-849"],
    flag: "./src/do.svg",
    isoCode2: "DO",
    isoCode3: "DOM",
  },
  {
    country: "East Timor",
    countryCodes: ["670"],
    flag: "./src/tl.svg",
    isoCode2: "TL",
    isoCode3: "TLS",
  },
  {
    country: "Ecuador",
    countryCodes: ["593"],
    flag: "./src/ec.svg",
    isoCode2: "EC",
    isoCode3: "ECU",
  },
  {
    country: "Egypt",
    countryCodes: ["20"],
    flag: "./src/eg.svg",
    isoCode2: "EG",
    isoCode3: "EGY",
  },
  {
    country: "El Salvador",
    countryCodes: ["503"],
    flag: "./src/sv.svg",
    isoCode2: "SV",
    isoCode3: "SLV",
  },
  {
    country: "Equatorial Guinea",
    countryCodes: ["240"],
    flag: "./src/gq.svg",
    isoCode2: "GQ",
    isoCode3: "GNQ",
  },
  {
    country: "Eritrea",
    countryCodes: ["291"],
    flag: "./src/er.svg",
    isoCode2: "ER",
    isoCode3: "ERI",
  },
  {
    country: "Estonia",
    countryCodes: ["372"],
    flag: "./src/ee.svg",
    isoCode2: "EE",
    isoCode3: "EST",
  },
  {
    country: "Ethiopia",
    countryCodes: ["251"],
    flag: "./src/et.svg",
    isoCode2: "ET",
    isoCode3: "ETH",
  },
  {
    country: "Falkland Islands",
    countryCodes: ["500"],
    flag: "./src/fk.svg",
    isoCode2: "FK",
    isoCode3: "FLK",
  },
  {
    country: "Faroe Islands",
    countryCodes: ["298"],
    flag: "./src/fo.svg",
    isoCode2: "FO",
    isoCode3: "FRO",
  },
  {
    country: "Fiji",
    countryCodes: ["679"],
    flag: "./src/fj.svg",
    isoCode2: "FJ",
    isoCode3: "FJI",
  },
  {
    country: "Finland",
    countryCodes: ["358"],
    flag: "./src/fi.svg",
    isoCode2: "FI",
    isoCode3: "FIN",
  },
  {
    country: "France",
    countryCodes: ["33"],
    flag: "./src/fr.svg",
    isoCode2: "FR",
    isoCode3: "FRA",
  },
  {
    country: "French Polynesia",
    countryCodes: ["689"],
    flag: "./src/pf.svg",
    isoCode2: "PF",
    isoCode3: "PYF",
  },
  {
    country: "Gabon",
    countryCodes: ["241"],
    flag: "./src/ga.svg",
    isoCode2: "GA",
    isoCode3: "GAB",
  },
  {
    country: "Gambia",
    countryCodes: ["220"],
    flag: "./src/gm.svg",
    isoCode2: "GM",
    isoCode3: "GMB",
  },
  {
    country: "Georgia",
    countryCodes: ["995"],
    flag: "./src/ge.svg",
    isoCode2: "GE",
    isoCode3: "GEO",
  },
  {
    country: "Germany",
    countryCodes: ["49"],
    flag: "./src/de.svg",
    isoCode2: "DE",
    isoCode3: "DEU",
  },
  {
    country: "Ghana",
    countryCodes: ["233"],
    flag: "./src/gh.svg",
    isoCode2: "GH",
    isoCode3: "GHA",
  },
  {
    country: "Gibraltar",
    countryCodes: ["350"],
    flag: "./src/gi.svg",
    isoCode2: "GI",
    isoCode3: "GIB",
  },
  {
    country: "Greece",
    countryCodes: ["30"],
    flag: "./src/gr.svg",
    isoCode2: "GR",
    isoCode3: "GRC",
  },
  {
    country: "Greenland",
    countryCodes: ["299"],
    flag: "./src/gl.svg",
    isoCode2: "GL",
    isoCode3: "GRL",
  },
  {
    country: "Grenada",
    countryCodes: ["1-473"],
    flag: "./src/gd.svg",
    isoCode2: "GD",
    isoCode3: "GRD",
  },
  {
    country: "Guam",
    countryCodes: ["1-671"],
    flag: "./src/gu.svg",
    isoCode2: "GU",
    isoCode3: "GUM",
  },
  {
    country: "Guatemala",
    countryCodes: ["502"],
    flag: "./src/gt.svg",
    isoCode2: "GT",
    isoCode3: "GTM",
  },
  {
    country: "Guernsey",
    countryCodes: ["44-1481"],
    flag: "./src/gg.svg",
    isoCode2: "GG",
    isoCode3: "GGY",
  },
  {
    country: "Guinea",
    countryCodes: ["224"],
    flag: "./src/gn.svg",
    isoCode2: "GN",
    isoCode3: "GIN",
  },
  {
    country: "Guinea-Bissau",
    countryCodes: ["245"],
    flag: "./src/gw.svg",
    isoCode2: "GW",
    isoCode3: "GNB",
  },
  {
    country: "Guyana",
    countryCodes: ["592"],
    flag: "./src/gy.svg",
    isoCode2: "GY",
    isoCode3: "GUY",
  },
  {
    country: "Haiti",
    countryCodes: ["509"],
    flag: "./src/ht.svg",
    isoCode2: "HT",
    isoCode3: "HTI",
  },
  {
    country: "Honduras",
    countryCodes: ["504"],
    flag: "./src/hn.svg",
    isoCode2: "HN",
    isoCode3: "HND",
  },
  {
    country: "Hong Kong",
    countryCodes: ["852"],
    flag: "./src/hk.svg",
    isoCode2: "HK",
    isoCode3: "HKG",
  },
  {
    country: "Hungary",
    countryCodes: ["36"],
    flag: "./src/hu.svg",
    isoCode2: "HU",
    isoCode3: "HUN",
  },
  {
    country: "Iceland",
    countryCodes: ["354"],
    flag: "./src/is.svg",
    isoCode2: "IS",
    isoCode3: "ISL",
  },
  {
    country: "India",
    countryCodes: ["91"],
    flag: "./src/in.svg",
    isoCode2: "IN",
    isoCode3: "IND",
  },
  {
    country: "Indonesia",
    countryCodes: ["62"],
    flag: "./src/id.svg",
    isoCode2: "ID",
    isoCode3: "IDN",
  },
  {
    country: "Iran",
    countryCodes: ["98"],
    flag: "./src/ir.svg",
    isoCode2: "IR",
    isoCode3: "IRN",
  },
  {
    country: "Iraq",
    countryCodes: ["964"],
    flag: "./src/iq.svg",
    isoCode2: "IQ",
    isoCode3: "IRQ",
  },
  {
    country: "Ireland",
    countryCodes: ["353"],
    flag: "./src/ie.svg",
    isoCode2: "IE",
    isoCode3: "IRL",
  },
  {
    country: "Isle of Man",
    countryCodes: ["44-1624"],
    flag: "./src/im.svg",
    isoCode2: "IM",
    isoCode3: "IMN",
  },
  {
    country: "Israel",
    countryCodes: ["972"],
    flag: "./src/il.svg",
    isoCode2: "IL",
    isoCode3: "ISR",
  },
  {
    country: "Italy",
    countryCodes: ["39"],
    flag: "./src/it.svg",
    isoCode2: "IT",
    isoCode3: "ITA",
  },
  {
    country: "Ivory Coast",
    countryCodes: ["225"],
    flag: "./src/ci.svg",
    isoCode2: "CI",
    isoCode3: "CIV",
  },
  {
    country: "Jamaica",
    countryCodes: ["1-876"],
    flag: "./src/jm.svg",
    isoCode2: "JM",
    isoCode3: "JAM",
  },
  {
    country: "Japan",
    countryCodes: ["81"],
    flag: "./src/jp.svg",
    isoCode2: "JP",
    isoCode3: "JPN",
  },
  {
    country: "Jersey",
    countryCodes: ["44-1534"],
    flag: "./src/je.svg",
    isoCode2: "JE",
    isoCode3: "JEY",
  },
  {
    country: "Jordan",
    countryCodes: ["962"],
    flag: "./src/jo.svg",
    isoCode2: "JO",
    isoCode3: "JOR",
  },
  {
    country: "Kazakhstan",
    countryCodes: ["7"],
    flag: "./src/kz.svg",
    isoCode2: "KZ",
    isoCode3: "KAZ",
  },
  {
    country: "Kenya",
    countryCodes: ["254"],
    flag: "./src/ke.svg",
    isoCode2: "KE",
    isoCode3: "KEN",
  },
  {
    country: "Kiribati",
    countryCodes: ["686"],
    flag: "./src/ki.svg",
    isoCode2: "KI",
    isoCode3: "KIR",
  },
  {
    country: "Kosovo",
    countryCodes: ["383"],
    flag: "./src/xk.svg",
    isoCode2: "XK",
    isoCode3: "XKX",
  },
  {
    country: "Kuwait",
    countryCodes: ["965"],
    flag: "./src/kw.svg",
    isoCode2: "KW",
    isoCode3: "KWT",
  },
  {
    country: "Kyrgyzstan",
    countryCodes: ["996"],
    flag: "./src/kg.svg",
    isoCode2: "KG",
    isoCode3: "KGZ",
  },
  {
    country: "Laos",
    countryCodes: ["856"],
    flag: "./src/la.svg",
    isoCode2: "LA",
    isoCode3: "LAO",
  },
  {
    country: "Latvia",
    countryCodes: ["371"],
    flag: "./src/lv.svg",
    isoCode2: "LV",
    isoCode3: "LVA",
  },
  {
    country: "Lebanon",
    countryCodes: ["961"],
    flag: "./src/lb.svg",
    isoCode2: "LB",
    isoCode3: "LBN",
  },
  {
    country: "Lesotho",
    countryCodes: ["266"],
    flag: "./src/ls.svg",
    isoCode2: "LS",
    isoCode3: "LSO",
  },
  {
    country: "Liberia",
    countryCodes: ["231"],
    flag: "./src/lr.svg",
    isoCode2: "LR",
    isoCode3: "LBR",
  },
  {
    country: "Libya",
    countryCodes: ["218"],
    flag: "./src/ly.svg",
    isoCode2: "LY",
    isoCode3: "LBY",
  },
  {
    country: "Liechtenstein",
    countryCodes: ["423"],
    flag: "./src/li.svg",
    isoCode2: "LI",
    isoCode3: "LIE",
  },
  {
    country: "Lithuania",
    countryCodes: ["370"],
    flag: "./src/lt.svg",
    isoCode2: "LT",
    isoCode3: "LTU",
  },
  {
    country: "Luxembourg",
    countryCodes: ["352"],
    flag: "./src/lu.svg",
    isoCode2: "LU",
    isoCode3: "LUX",
  },
  {
    country: "Macau",
    countryCodes: ["853"],
    flag: "./src/mo.svg",
    isoCode2: "MO",
    isoCode3: "MAC",
  },
  {
    country: "Macedonia",
    countryCodes: ["389"],
    flag: "./src/mk.svg",
    isoCode2: "MK",
    isoCode3: "MKD",
  },
  {
    country: "Madagascar",
    countryCodes: ["261"],
    flag: "./src/mg.svg",
    isoCode2: "MG",
    isoCode3: "MDG",
  },
  {
    country: "Malawi",
    countryCodes: ["265"],
    flag: "./src/mw.svg",
    isoCode2: "MW",
    isoCode3: "MWI",
  },
  {
    country: "Malaysia",
    countryCodes: ["60"],
    flag: "./src/my.svg",
    isoCode2: "MY",
    isoCode3: "MYS",
  },
  {
    country: "Maldives",
    countryCodes: ["960"],
    flag: "./src/mv.svg",
    isoCode2: "MV",
    isoCode3: "MDV",
  },
  {
    country: "Mali",
    countryCodes: ["223"],
    flag: "./src/ml.svg",
    isoCode2: "ML",
    isoCode3: "MLI",
  },
  {
    country: "Malta",
    countryCodes: ["356"],
    flag: "./src/mt.svg",
    isoCode2: "MT",
    isoCode3: "MLT",
  },
  {
    country: "Marshall Islands",
    countryCodes: ["692"],
    flag: "./src/mh.svg",
    isoCode2: "MH",
    isoCode3: "MHL",
  },
  {
    country: "Mauritania",
    countryCodes: ["222"],
    flag: "./src/mr.svg",
    isoCode2: "MR",
    isoCode3: "MRT",
  },
  {
    country: "Mauritius",
    countryCodes: ["230"],
    flag: "./src/mu.svg",
    isoCode2: "MU",
    isoCode3: "MUS",
  },
  {
    country: "Mayotte",
    countryCodes: ["262"],
    flag: "./src/yt.svg",
    isoCode2: "YT",
    isoCode3: "MYT",
  },
  {
    country: "Mexico",
    countryCodes: ["52"],
    flag: "./src/mx.svg",
    isoCode2: "MX",
    isoCode3: "MEX",
  },
  {
    country: "Micronesia",
    countryCodes: ["691"],
    flag: "./src/fm.svg",
    isoCode2: "FM",
    isoCode3: "FSM",
  },
  {
    country: "Moldova",
    countryCodes: ["373"],
    flag: "./src/md.svg",
    isoCode2: "MD",
    isoCode3: "MDA",
  },
  {
    country: "Monaco",
    countryCodes: ["377"],
    flag: "./src/mc.svg",
    isoCode2: "MC",
    isoCode3: "MCO",
  },
  {
    country: "Mongolia",
    countryCodes: ["976"],
    flag: "./src/mn.svg",
    isoCode2: "MN",
    isoCode3: "MNG",
  },
  {
    country: "Montenegro",
    countryCodes: ["382"],
    flag: "./src/me.svg",
    isoCode2: "ME",
    isoCode3: "MNE",
  },
  {
    country: "Montserrat",
    countryCodes: ["1-664"],
    flag: "./src/ms.svg",
    isoCode2: "MS",
    isoCode3: "MSR",
  },
  {
    country: "Morocco",
    countryCodes: ["212"],
    flag: "./src/ma.svg",
    isoCode2: "MA",
    isoCode3: "MAR",
  },
  {
    country: "Mozambique",
    countryCodes: ["258"],
    flag: "./src/mz.svg",
    isoCode2: "MZ",
    isoCode3: "MOZ",
  },
  {
    country: "Myanmar",
    countryCodes: ["95"],
    flag: "./src/mm.svg",
    isoCode2: "MM",
    isoCode3: "MMR",
  },
  {
    country: "Namibia",
    countryCodes: ["264"],
    flag: "./src/na.svg",
    isoCode2: "NA",
    isoCode3: "NAM",
  },
  {
    country: "Nauru",
    countryCodes: ["674"],
    flag: "./src/nr.svg",
    isoCode2: "NR",
    isoCode3: "NRU",
  },
  {
    country: "Nepal",
    countryCodes: ["977"],
    flag: "./src/np.svg",
    isoCode2: "NP",
    isoCode3: "NPL",
  },
  {
    country: "Netherlands",
    countryCodes: ["31"],
    flag: "./src/nl.svg",
    isoCode2: "NL",
    isoCode3: "NLD",
  },
  {
    country: "Netherlands Antilles",
    countryCodes: ["599"],
    flag: "./src/an.svg",
    isoCode2: "AN",
    isoCode3: "ANT",
  },
  {
    country: "New Caledonia",
    countryCodes: ["687"],
    flag: "./src/nc.svg",
    isoCode2: "NC",
    isoCode3: "NCL",
  },
  {
    country: "New Zealand",
    countryCodes: ["64"],
    flag: "./src/nz.svg",
    isoCode2: "NZ",
    isoCode3: "NZL",
  },
  {
    country: "Nicaragua",
    countryCodes: ["505"],
    flag: "./src/ni.svg",
    isoCode2: "NI",
    isoCode3: "NIC",
  },
  {
    country: "Niger",
    countryCodes: ["227"],
    flag: "./src/ne.svg",
    isoCode2: "NE",
    isoCode3: "NER",
  },
  {
    country: "Nigeria",
    countryCodes: ["234"],
    flag: "./src/ng.svg",
    isoCode2: "NG",
    isoCode3: "NGA",
  },
  {
    country: "North Korea",
    countryCodes: ["850"],
    flag: "./src/kp.svg",
    isoCode2: "KP",
    isoCode3: "PRK",
  },
  {
    country: "Northern Mariana Islands",
    countryCodes: ["1-670"],
    flag: "./src/mp.svg",
    isoCode2: "MP",
    isoCode3: "MNP",
  },
  {
    country: "Norway",
    countryCodes: ["47"],
    flag: "./src/no.svg",
    isoCode2: "NO",
    isoCode3: "NOR",
  },
  {
    country: "Oman",
    countryCodes: ["968"],
    flag: "./src/om.svg",
    isoCode2: "OM",
    isoCode3: "OMN",
  },
  {
    country: "Pakistan",
    countryCodes: ["92"],
    flag: "./src/pk.svg",
    isoCode2: "PK",
    isoCode3: "PAK",
  },
  {
    country: "Palau",
    countryCodes: ["680"],
    flag: "./src/pw.svg",
    isoCode2: "PW",
    isoCode3: "PLW",
  },
  {
    country: "Palestine",
    countryCodes: ["970"],
    flag: "./src/ps.svg",
    isoCode2: "PS",
    isoCode3: "PSE",
  },
  {
    country: "Panama",
    countryCodes: ["507"],
    flag: "./src/pa.svg",
    isoCode2: "PA",
    isoCode3: "PAN",
  },
  {
    country: "Papua New Guinea",
    countryCodes: ["675"],
    flag: "./src/pg.svg",
    isoCode2: "PG",
    isoCode3: "PNG",
  },
  {
    country: "Paraguay",
    countryCodes: ["595"],
    flag: "./src/py.svg",
    isoCode2: "PY",
    isoCode3: "PRY",
  },
  {
    country: "Peru",
    countryCodes: ["51"],
    flag: "./src/pe.svg",
    isoCode2: "PE",
    isoCode3: "PER",
  },
  {
    country: "Philippines",
    countryCodes: ["63"],
    flag: "./src/ph.svg",
    isoCode2: "PH",
    isoCode3: "PHL",
  },
  {
    country: "Pitcairn",
    countryCodes: ["64"],
    flag: "./src/pn.svg",
    isoCode2: "PN",
    isoCode3: "PCN",
  },
  {
    country: "Poland",
    countryCodes: ["48"],
    flag: "./src/pl.svg",
    isoCode2: "PL",
    isoCode3: "POL",
  },
  {
    country: "Portugal",
    countryCodes: ["351"],
    flag: "./src/pt.svg",
    isoCode2: "PT",
    isoCode3: "PRT",
  },
  {
    country: "Puerto Rico",
    countryCodes: ["1-787", "1-939"],
    flag: "./src/pr.svg",
    isoCode2: "PR",
    isoCode3: "PRI",
  },
  {
    country: "Qatar",
    countryCodes: ["974"],
    flag: "./src/qa.svg",
    isoCode2: "QA",
    isoCode3: "QAT",
  },
  {
    country: "Republic of the Congo",
    countryCodes: ["242"],
    flag: "./src/cg.svg",
    isoCode2: "CG",
    isoCode3: "COG",
  },
  {
    country: "Reunion",
    countryCodes: ["262"],
    flag: "./src/re.svg",
    isoCode2: "RE",
    isoCode3: "REU",
  },
  {
    country: "Romania",
    countryCodes: ["40"],
    flag: "./src/ro.svg",
    isoCode2: "RO",
    isoCode3: "ROU",
  },
  {
    country: "Russia",
    countryCodes: ["7"],
    flag: "./src/ru.svg",
    isoCode2: "RU",
    isoCode3: "RUS",
  },
  {
    country: "Rwanda",
    countryCodes: ["250"],
    flag: "./src/rw.svg",
    isoCode2: "RW",
    isoCode3: "RWA",
  },
  {
    country: "Saint Barthelemy",
    countryCodes: ["590"],
    flag: "./src/bl.svg",
    isoCode2: "BL",
    isoCode3: "BLM",
  },
  {
    country: "Saint Helena",
    countryCodes: ["290"],
    flag: "./src/sh.svg",
    isoCode2: "SH",
    isoCode3: "SHN",
  },
  {
    country: "Saint Kitts and Nevis",
    countryCodes: ["1-869"],
    flag: "./src/kn.svg",
    isoCode2: "KN",
    isoCode3: "KNA",
  },
  {
    country: "Saint Lucia",
    countryCodes: ["1-758"],
    flag: "./src/lc.svg",
    isoCode2: "LC",
    isoCode3: "LCA",
  },
  {
    country: "Saint Martin",
    countryCodes: ["590"],
    flag: "./src/mf.svg",
    isoCode2: "MF",
    isoCode3: "MAF",
  },
  {
    country: "Saint Pierre and Miquelon",
    countryCodes: ["508"],
    flag: "./src/pm.svg",
    isoCode2: "PM",
    isoCode3: "SPM",
  },
  {
    country: "Saint Vincent and the Grenadines",
    countryCodes: ["1-784"],
    flag: "./src/vc.svg",
    isoCode2: "VC",
    isoCode3: "VCT",
  },
  {
    country: "Samoa",
    countryCodes: ["685"],
    flag: "./src/ws.svg",
    isoCode2: "WS",
    isoCode3: "WSM",
  },
  {
    country: "San Marino",
    countryCodes: ["378"],
    flag: "./src/sm.svg",
    isoCode2: "SM",
    isoCode3: "SMR",
  },
  {
    country: "Sao Tome and Principe",
    countryCodes: ["239"],
    flag: "./src/st.svg",
    isoCode2: "ST",
    isoCode3: "STP",
  },
  {
    country: "Saudi Arabia",
    countryCodes: ["966"],
    flag: "./src/sa.svg",
    isoCode2: "SA",
    isoCode3: "SAU",
  },
  {
    country: "Senegal",
    countryCodes: ["221"],
    flag: "./src/sn.svg",
    isoCode2: "SN",
    isoCode3: "SEN",
  },
  {
    country: "Serbia",
    countryCodes: ["381"],
    flag: "./src/rs.svg",
    isoCode2: "RS",
    isoCode3: "SRB",
  },
  {
    country: "Seychelles",
    countryCodes: ["248"],
    flag: "./src/sc.svg",
    isoCode2: "SC",
    isoCode3: "SYC",
  },
  {
    country: "Sierra Leone",
    countryCodes: ["232"],
    flag: "./src/sl.svg",
    isoCode2: "SL",
    isoCode3: "SLE",
  },
  {
    country: "Singapore",
    countryCodes: ["65"],
    flag: "./src/sg.svg",
    isoCode2: "SG",
    isoCode3: "SGP",
  },
  {
    country: "Sint Maarten",
    countryCodes: ["1-721"],
    flag: "./src/sx.svg",
    isoCode2: "SX",
    isoCode3: "SXM",
  },
  {
    country: "Slovakia",
    countryCodes: ["421"],
    flag: "./src/sk.svg",
    isoCode2: "SK",
    isoCode3: "SVK",
  },
  {
    country: "Slovenia",
    countryCodes: ["386"],
    flag: "./src/si.svg",
    isoCode2: "SI",
    isoCode3: "SVN",
  },
  {
    country: "Solomon Islands",
    countryCodes: ["677"],
    flag: "./src/sb.svg",
    isoCode2: "SB",
    isoCode3: "SLB",
  },
  {
    country: "Somalia",
    countryCodes: ["252"],
    flag: "./src/so.svg",
    isoCode2: "SO",
    isoCode3: "SOM",
  },
  {
    country: "South Africa",
    countryCodes: ["27"],
    flag: "./src/za.svg",
    isoCode2: "ZA",
    isoCode3: "ZAF",
  },
  {
    country: "South Korea",
    countryCodes: ["82"],
    flag: "./src/kr.svg",
    isoCode2: "KR",
    isoCode3: "KOR",
  },
  {
    country: "South Sudan",
    countryCodes: ["211"],
    flag: "./src/ss.svg",
    isoCode2: "SS",
    isoCode3: "SSD",
  },
  {
    country: "Spain",
    countryCodes: ["34"],
    flag: "./src/es.svg",
    isoCode2: "ES",
    isoCode3: "ESP",
  },
  {
    country: "Sri Lanka",
    countryCodes: ["94"],
    flag: "./src/lk.svg",
    isoCode2: "LK",
    isoCode3: "LKA",
  },
  {
    country: "Sudan",
    countryCodes: ["249"],
    flag: "./src/sd.svg",
    isoCode2: "SD",
    isoCode3: "SDN",
  },
  {
    country: "Suriname",
    countryCodes: ["597"],
    flag: "./src/sr.svg",
    isoCode2: "SR",
    isoCode3: "SUR",
  },
  {
    country: "Svalbard and Jan Mayen",
    countryCodes: ["47"],
    flag: "./src/sj.svg",
    isoCode2: "SJ",
    isoCode3: "SJM",
  },
  {
    country: "Swaziland",
    countryCodes: ["268"],
    flag: "./src/sz.svg",
    isoCode2: "SZ",
    isoCode3: "SWZ",
  },
  {
    country: "Sweden",
    countryCodes: ["46"],
    flag: "./src/se.svg",
    isoCode2: "SE",
    isoCode3: "SWE",
  },
  {
    country: "Switzerland",
    countryCodes: ["41"],
    flag: "./src/ch.svg",
    isoCode2: "CH",
    isoCode3: "CHE",
  },
  {
    country: "Syria",
    countryCodes: ["963"],
    flag: "./src/sy.svg",
    isoCode2: "SY",
    isoCode3: "SYR",
  },
  {
    country: "Taiwan",
    countryCodes: ["886"],
    flag: "./src/tw.svg",
    isoCode2: "TW",
    isoCode3: "TWN",
  },
  {
    country: "Tajikistan",
    countryCodes: ["992"],
    flag: "./src/tj.svg",
    isoCode2: "TJ",
    isoCode3: "TJK",
  },
  {
    country: "Tanzania",
    countryCodes: ["255"],
    flag: "./src/tz.svg",
    isoCode2: "TZ",
    isoCode3: "TZA",
  },
  {
    country: "Thailand",
    countryCodes: ["66"],
    flag: "./src/th.svg",
    isoCode2: "TH",
    isoCode3: "THA",
  },
  {
    country: "Togo",
    countryCodes: ["228"],
    flag: "./src/tg.svg",
    isoCode2: "TG",
    isoCode3: "TGO",
  },
  {
    country: "Tokelau",
    countryCodes: ["690"],
    flag: "./src/tk.svg",
    isoCode2: "TK",
    isoCode3: "TKL",
  },
  {
    country: "Tonga",
    countryCodes: ["676"],
    flag: "./src/to.svg",
    isoCode2: "TO",
    isoCode3: "TON",
  },
  {
    country: "Trinidad and Tobago",
    countryCodes: ["1-868"],
    flag: "./src/tt.svg",
    isoCode2: "TT",
    isoCode3: "TTO",
  },
  {
    country: "Tunisia",
    countryCodes: ["216"],
    flag: "./src/tn.svg",
    isoCode2: "TN",
    isoCode3: "TUN",
  },
  {
    country: "Turkey",
    countryCodes: ["90"],
    flag: "./src/tr.svg",
    isoCode2: "TR",
    isoCode3: "TUR",
  },
  {
    country: "Turkmenistan",
    countryCodes: ["993"],
    flag: "./src/tm.svg",
    isoCode2: "TM",
    isoCode3: "TKM",
  },
  {
    country: "Turks and Caicos Islands",
    countryCodes: ["1-649"],
    flag: "./src/tc.svg",
    isoCode2: "TC",
    isoCode3: "TCA",
  },
  {
    country: "Tuvalu",
    countryCodes: ["688"],
    flag: "./src/tv.svg",
    isoCode2: "TV",
    isoCode3: "TUV",
  },
  {
    country: "U.S. Virgin Islands",
    countryCodes: ["1-340"],
    flag: "./src/vi.svg",
    isoCode2: "VI",
    isoCode3: "VIR",
  },
  {
    country: "Uganda",
    countryCodes: ["256"],
    flag: "./src/ug.svg",
    isoCode2: "UG",
    isoCode3: "UGA",
  },
  {
    country: "Ukraine",
    countryCodes: ["380"],
    flag: "./src/ua.svg",
    isoCode2: "UA",
    isoCode3: "UKR",
  },
  {
    country: "United Arab Emirates",
    countryCodes: ["971"],
    flag: "./src/ae.svg",
    isoCode2: "AE",
    isoCode3: "ARE",
  },
  {
    country: "United Kingdom",
    countryCodes: ["44"],
    flag: "./src/gb.svg",
    isoCode2: "GB",
    isoCode3: "GBR",
  },
  {
    country: "United States",
    countryCodes: ["1"],
    flag: "./src/us.svg",
    isoCode2: "US",
    isoCode3: "USA",
  },
  {
    country: "Uruguay",
    countryCodes: ["598"],
    flag: "./src/uy.svg",
    isoCode2: "UY",
    isoCode3: "URY",
  },
  {
    country: "Uzbekistan",
    countryCodes: ["998"],
    flag: "./src/uz.svg",
    isoCode2: "UZ",
    isoCode3: "UZB",
  },
  {
    country: "Vanuatu",
    countryCodes: ["678"],
    flag: "./src/vu.svg",
    isoCode2: "VU",
    isoCode3: "VUT",
  },
  {
    country: "Vatican",
    countryCodes: ["379"],
    flag: "./src/va.svg",
    isoCode2: "VA",
    isoCode3: "VAT",
  },
  {
    country: "Venezuela",
    countryCodes: ["58"],
    flag: "./src/ve.svg",
    isoCode2: "VE",
    isoCode3: "VEN",
  },
  {
    country: "Vietnam",
    countryCodes: ["84"],
    flag: "./src/vn.svg",
    isoCode2: "VN",
    isoCode3: "VNM",
  },
  {
    country: "Wallis and Futuna",
    countryCodes: ["681"],
    flag: "./src/wf.svg",
    isoCode2: "WF",
    isoCode3: "WLF",
  },
  {
    country: "Western Sahara",
    countryCodes: ["212"],
    flag: "./src/eh.svg",
    isoCode2: "EH",
    isoCode3: "ESH",
  },
  {
    country: "Yemen",
    countryCodes: ["967"],
    flag: "./src/ye.svg",
    isoCode2: "YE",
    isoCode3: "YEM",
  },
  {
    country: "Zambia",
    countryCodes: ["260"],
    flag: "./src/zm.svg",
    isoCode2: "ZM",
    isoCode3: "ZMB",
  },
  {
    country: "Zimbabwe",
    countryCodes: ["263"],
    flag: "./src/zw.svg",
    isoCode2: "ZW",
    isoCode3: "ZWE",
  },
];

module.exports = { countriesData };
